# Generated by Django 2.0.13 on 2019-03-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0004_threadedcomment_failed_automod'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadedcomment',
            name='chamber',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
